service: japanese-number-plates-detection

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.10
  stage: production
  region: ap-northeast-1
  iam:
    role:
      name: ${self:service}-lambda-Role

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
